//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Product_Descprition { get; set; }
        public decimal MRP { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
